apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ee62baxzo-python 
  janus-idp.io/tekton: ee62baxzo-python
  backstage.io/kubernetes-id: ee62baxzo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ee62baxzo-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  