apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ee62baxzo-python
  janus-idp.io/tekton: ee62baxzo-python
  backstage.io/kubernetes-id: ee62baxzo-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ee62baxzo-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
